version: 1.0.{build}
nuget:
  account_feed: true
  
configuration: Release
  
branches:
  # whitelist
  only:
    - master
      
before_build:
  - nuget restore
  
after_build:
  - nuget pack Gaucho.Forms.nuspec
  
deploy:
  - provider: NuGet
    symbol_server: %ACCOUNT_FEED%
    api_key:
      secure: %SECRET_KEY%
    artifact: /.*\.symbols\.nupkg/
    
test:
  assemblies: Gaucho.Forms.Core.UnitTests\bin\Debug\Gaucho.Forms.Core.UnitTests.dll