// <auto-generated/>
using System.Reflection;

[assembly: AssemblyProductAttribute("Gaucho.Forms")]
[assembly: AssemblyVersionAttribute("1.0.2")]
[assembly: AssemblyFileVersionAttribute("1.0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyProduct = "Gaucho.Forms";
        internal const System.String AssemblyVersion = "1.0.2";
        internal const System.String AssemblyFileVersion = "1.0.2";
    }
}
